name: Node.js Package

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.trim.outputs.version }}
    steps:
      - id: trim
        run: echo "::set-output name=version::${TAG:1}"
        env:
          TAG: ${{ github.event.release.tag_name }}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Test
      run: |
        npm ci
        xvfb-run --auto-servernum npm test

  publish-npm:
    needs: [test, setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup and build
        run: |
          npm ci
          npm install -g json
          json -I -f package.json -e "this.version=\"$VERSION\""
          json -I -f package-lock.json -e "this.version=\"$VERSION\""
          npm run build
          npm pack
        env:
          VERSION: ${{ needs.setup.outputs.version }}
      - name: Publish @next
        run: npm publish --tag next
        if: "github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish @latest
        run: npm publish --tag latest --dry-run
        if: "!github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
